//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTable
    {
        public string dates { get; set; }
        public double avg_gas_price { get; set; }
    }
}
