//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentoring_Session_1._30._24
{
    using System;
    using System.Collections.Generic;

    public partial class testTable
    {
        public string Name { get; set; }
        public string Gender { get; set; }

        public testTable() { }

        // CONSTRUCTOR
        public testTable(string name, string gender)
        {
            Name = name;
            Gender = gender;
        }
        // RANDOM PERSON GENERATOR
        public static testTable GeneratePerson()
        {
            string[] names = { "John", "Jane", "Alice", "Bob", "Emily", "Michael" };
            string[] genders = { "M", "F" };

            Random random = new Random();
            int randomNumber = random.Next(100, 1000);
            string numberString = randomNumber.ToString();

            string randomName = names[random.Next(names.Length)] + numberString; // ADDING NUMBER TO AVOID TRIPPING THE PRIMARY KEY
            string randomGender = genders[random.Next(genders.Length)];

            // RETURN NEW PERSON VALUE
            return new testTable(randomName, randomGender);
        }
    }

}
